resource_types:
- name: mysql-releases
  type: docker-image
  source:
    repository: cryogenics/mysql-releases-resource

resources:
- name: backup-and-restore-sdk-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-sdk-release.git
    private_key: ((github.ssh_key))
    branch: develop

- name: backup-and-restore-sdk-release-vendoring
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-sdk-release.git
    private_key: ((github.ssh_key))
    branch: golang-vendor-updates

- name: backup-and-restore-sdk-mysql-blob-updates
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-sdk-release.git
    private_key: ((github.ssh_key))
    branch: mysql-blob-updates

- name: golang-release
  type: git
  source:
    uri: https://github.com/bosh-packages/golang-release.git
    tag_filter: v*

- name: cryogenics-meta
  type: git
  source:
    uri: git@github.com:pivotal-cf/cryogenics-meta.git
    private_key: ((github.ssh_key))
    branch: main

- name: mysql-5.6-release
  type: mysql-releases
  source:
    product: MySQL Community Server 5.6

jobs:
- name: bump-golang
  plan:
  - in_parallel:
    - get: cryogenics-meta
    - get: golang-release
      trigger: true
    - get: backup-and-restore-sdk-release
  - task: bosh-vendor-package
    file: cryogenics-meta/ci/tasks/bosh-vendor-package/task.yml
    input_mapping:
      release: backup-and-restore-sdk-release
      vendored-package-release: golang-release
    params:
      VENDORED_PACKAGE_NAME: golang-1-linux
      VENDOR_UPDATES_BRANCH: golang-vendor-updates
      COMMIT_USERNAME: bump-golang CI job
      COMMIT_USEREMAIL: mapbu-cryogenics@groups.vmware.com
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))
  - put: backup-and-restore-sdk-release-vendoring
    params:
      repository: release-with-updated-vendored-package
      branch: golang-vendor-updates
      force: true
  - task: create-golang-vendor-pull-request
    file: cryogenics-meta/ci/tasks/create-pr/task.yml
    params:
      LABELS: ci,bump-golang
      GITHUB_TOKEN: ((github.access_token))
      BASE: develop
      BRANCH: golang-vendor-updates
      TITLE: Update vendored package golang-1-linux
      MESSAGE:
        This is an automatically generated Pull Request from the Cryogenics CI Bot.

        I have detected a new version of [golang-release](https://github.com/bosh-packages/golang-release) and automatically bumped
        this package to benefit from the latest changes.

        If this does not look right, please reach out to the [#mapbu-cryogenics](https://vmware.slack.com/archives/C01DXEYRKRU) team.
    input_mapping:
      repo: backup-and-restore-sdk-release-vendoring
- name: bump-mysql
  plan:
  - in_parallel:
    - get: cryogenics-meta
    - get: backup-and-restore-sdk-release
    - get: mysql-5.6-release
      trigger: true
  - task: bump-mysql-5.6
    file: backup-and-restore-sdk-release/ci/tasks/bump-mysql-5.6/task.yml
    params:
      VENDOR_UPDATES_BRANCH: mysql-blob-updates
      COMMIT_USERNAME: bump-mysql CI job
      COMMIT_USEREMAIL: mapbu-cryogenics@groups.vmware.com
      AWS_ACCESS_KEY_ID: ((aws_credentials.access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_credentials.secret_access_key))
  - put: backup-and-restore-sdk-mysql-blob-updates
    params:
      repository: release-with-updated-mysql-release
      branch: mysql-blob-updates
      force: true
  - task: create-golang-vendor-pull-request
    file: cryogenics-meta/ci/tasks/create-pr/task.yml
    params:
      LABELS: ci,bump-mysql,dependencies
      GITHUB_TOKEN: ((github.access_token))
      BASE: develop
      BRANCH: mysql-blob-updates
      TITLE: Update blob mysql-5.6
      MESSAGE:
        This is an automatically generated Pull Request from the Cryogenics CI Bot.

        I have detected a new version of [mysql 5.6](https://dev.mysql.com/doc/relnotes/mysql/5.6/en/) and automatically bumped
        this package to benefit from the latest changes.

        If this does not look right, please reach out to the [#mapbu-cryogenics](https://vmware.slack.com/archives/C01DXEYRKRU) team.
    input_mapping:
      repo: backup-and-restore-sdk-mysql-blob-updates