---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: backup-and-restore-sdk-release

outputs:
- name: tracker-story

run:
  path: backup-and-restore-sdk-release/ci/tasks/find-pr-story/task.sh