---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: backup-and-restore-sdk-release

run:
  path: backup-and-restore-sdk-release/ci/tasks/accept-stories/task.sh