platform: linux
image_resource:
  type: registry-image
  source:
    repository: bosh/bosh-ecosystem-concourse
    username: ((docker.username))
    password: ((docker.password))
inputs:
  - name: backup-and-restore-sdk-release
run:
  path: bash
  args:
    - -e
    - -c
    - |
      cd backup-and-restore-sdk-release
      set -u -o pipefail
      echo 'gem: --no-document' > /etc/gemrc
      NUM_CPUS=$(grep -c ^processor /proc/cpuinfo)
      RUBY_VERSION="$(cat .ruby-version)"
      ruby-install --jobs="${NUM_CPUS}" --cleanup --system ruby "${RUBY_VERSION}"

      bundle install
      bundle exec rspec
