platform: linux
image_resource:
  type: registry-image
  source:
    repository: bosh/bosh-ecosystem-concourse
    username: ((docker.username))
    password: ((docker.password))
inputs:
  - name: backup-and-restore-sdk-release
  - name: ruby-install
run:
  path: bash
  args:
    - -e
    - -c
    - |
      set -u -o pipefail
      pushd ruby-install
        make install
      popd
      pushd backup-and-restore-sdk-release

        echo 'gem: --no-document' > /etc/gemrc
        NUM_CPUS=$(grep -c ^processor /proc/cpuinfo)
        RUBY_VERSION="$(cat .ruby-version)"
        ruby-install --jobs="${NUM_CPUS}" --cleanup --system ruby "${RUBY_VERSION}"

        bundle install
        bundle exec rspec
      popd
